ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoThemeWatchEnabled"    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoThemeWatchFrequency"  TEXT    NOT NULL DEFAULT 'weekly';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoProductDropEnabled"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoProductDropFrequency" TEXT    NOT NULL DEFAULT 'daily';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoSeoFixEnabled"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "autoSeoFixFrequency"      TEXT    NOT NULL DEFAULT 'weekly';
